CNN model

In [1]:
import os
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from PIL import Image
import random
from sklearn.metrics import f1_score
###### import your HW4 code######
from Dense import Dense
from Activation import Activation
from Loss import compute_BCE_loss
from Predict import predict
from preprocess_image import preprocess_image
##################################

output = {}
seed = 1
np.random.seed(seed)

In [2]:
data, labels = preprocess_image()
data

begin
reading from H:\我的雲端硬碟\jay chou\total_notJay\...
progress: 19.217491369390103 %
progress: 38.39662447257383 %
progress: 57.57575757575758 %
progress: 76.75489067894131 %
progress: 95.93402378212504 %
finish reading from H:\我的雲端硬碟\jay chou\total_notJay\
(2606, 180, 180)
reading from H:\我的雲端硬碟\jay chou\total_Jay\...
progress: 10.612158441008262 %
progress: 21.203134929040456 %
progress: 31.794111417072656 %
progress: 42.385087905104854 %
progress: 52.976064393137044 %
progress: 63.56704088116925 %
progress: 74.15801736920145 %
progress: 84.74899385723363 %
progress: 95.33997034526584 %
finish reading from H:\我的雲端硬碟\jay chou\total_Jay\
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
(7326, 180, 180)
(7326, 1)


array([[[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
        ...,
        [1.0, 1.0, 1.0, ..., 0.0, 0.0, 0.0],
        [1.0, 1.0, 1.0, ..., 0.0, 0.0, 0.0],
        [1.0, 1.0, 1.0, ..., 0.0, 0.0, 0.0]],

       [[0.0, 0.0, 0.0, ..., 1.0, 1.0, 1.0],
        [0.0, 0.0, 0.0, ..., 1.0, 1.0, 1.0],
        [0.0, 0.0, 0.0, ..., 1.0, 1.0, 1.0],
        ...,
        [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]],

       [[1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0],
        [1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0],
        [1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0],
        ...,
        [1.0, 1.0, 1.0, ..., 0.0, 0.0, 0.0],
        [1.0, 1.0, 1.0, ..., 0.0, 0.0, 0.0],
        [1.0, 1.0, 1.0, ..., 0.0, 0.0, 1.0]],

       ...,

       [[0.0, 0.0, 0.0, ..., 1.0, 1.0, 1.0],
        [0.0, 0.0, 0.0, ..., 1.0, 1.0, 1.0],
        [0.0, 0.0, 0.0, ..., 1.0, 1.0, 1.0

In [3]:
data = data.reshape(7326,180,180,1)
print(data)
print(data.shape)

[[[[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]

  [[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]

  [[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]

  ...

  [[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]

  [[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]

  [[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]]


 [[[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]

  [[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]

  [[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]

  ...

  [[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]

  [[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]

  [[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]]


 [[[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]

  [[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]

  [[1.0]
   [1.0]
   [1.0]
   ...
   [1.0]
   [1.0]
   [1.0]]

  ...

  [[1.0]
   [1.0]
   [1.0]
   

In [4]:
np.save('data_CNN.npy', data)
np.save('labels_CNN.npy', labels)

In [4]:
class Conv():
    def __init__(self, filter_size=2, input_channel=3, output_channel=8, pad=1, stride=1, seed=1):

        self.filter_size= filter_size
        self.input_channel=input_channel
        self.output_channel=output_channel
        self.seed = seed
        self.pad = pad
        self.stride = stride

        self.parameters = {'W':None, 'b': None}
        self.initialize_parameters()

    def initialize_parameters(self):
        """
        self.parameters -- python dictionary containing your parameters:
        W -- weight matrix of shape (filter_size, filter_size, input channel size, output channel size)
        b -- bias vector of shape (1, 1, 1, output channel size)
        """
        np.random.seed(seed)
        sd = np.sqrt(6.0 / (self.input_channel + self.output_channel))
        W = np.random.uniform(-sd, sd, (self.filter_size,self.filter_size,self.input_channel,self.output_channel))
        b = np.zeros((1, 1, 1, self.output_channel))

        assert(W.shape == (self.filter_size,self.filter_size,self.input_channel,self.output_channel))
        assert(b.shape == (1,1,1,self.output_channel))

        self.parameters['W'] = W
        self.parameters['b'] = b

In [5]:
def zero_pad(X, pad):
    """
    Pad all images in the dataset X with zeros. The padding should be applied to both the height and width of each image.

    Argument:
    X -- python numpy array of shape (m, n_H, n_W, n_C), where m represent the number of examples.
    pad -- integer, amount of padding around each image on vertical and horizontal dimensions

    Returns:
    X_pad -- padded image of shape (m, n_H + 2*pad, n_W + 2*pad, n_C)
    """

    ### START CODE HERE ###
    X_pad = np.pad(X, ((0,0),(pad, pad), (pad, pad), (0,0)), "constant", constant_values=(0,0))
    ### END CODE HERE ###

    return X_pad

In [6]:
def conv_single_step(self, a_slice_prev, W, b):
        """
        Arguments:
        a_slice_prev -- slice of previous activation layer output with shape (filter_size, filter_size, n_C_prev)
        W -- Weight parameters contained in a window - matrix of shape (filter_size, filter_size, n_C_prev)
        b -- Bias parameters contained in a window - matrix of shape (1, 1, 1)

        Returns:
        Z -- a scalar value, result of convolving the sliding window (W, b) on a slice x of the input data
        """

        ### START CODE HERE ### (≈ 3 lines)
        # Step 1: Element-wise product to a_slice_prev and W
        filtered = a_slice_prev * W
        # Step 2: Sum all values to get a single scalar
        Z = np.sum(filtered)
        # Step 3: Add the bias
        Z = Z + np.squeeze(b)
        ### END CODE HERE ###

        return Z

Conv.conv_single_step = conv_single_step

In [7]:

def forward(self, A_prev):
    """
    Implements the forward propagation for a convolution layer

    Arguments:
    A_prev -- output activations of the previous layer, numpy array of shape (m, n_H_prev, n_W_prev, n_C_prev)

    Returns:
    Z -- conv output, numpy array of shape (m, n_H, n_W, n_C)
    """

    ### START CODE HERE ###
    # Retrieve dimensions from A_prev's shape
    print(A_prev.shape)
    (m, n_H_prev, n_W_prev, n_C_prev) = A_prev.shape

    # Retrieve dimensions from W's shape
    (f, f, n_C_prev, n_C) = self.parameters["W"].shape


    # Step 1: Output Dimension Calculation
    pad = self.pad
    stride = self.stride
    n_H = int(np.floor(n_H_prev - self.filter_size + 2 * pad)/self.stride + 1)
    n_W = int(np.floor(n_W_prev - self.filter_size + 2 * pad)/self.stride + 1)

    # Initialize the output volume Z with zeros
    Z = np.zeros((m, n_H, n_W, n_C))
    # Step 2: Padding
    A_prev_pad = zero_pad(A_prev, pad)

    # Step 3: Loop Through Training Examples
    for i in range(m):                                 # loop over the batch of training examples
        for h in range(n_H):                           # loop over vertical axis of the output volume
            for w in range(n_W):                       # loop over horizontal axis of the output volume
                for c in range(n_C):                   # loop over channels (= #filter) of the output volume


                    # Step 3-1: Extracting slices
                    vert_start = h * self.stride
                    vert_end = vert_start + self.filter_size
                    horiz_start = w * self.stride
                    horiz_end = horiz_start + self.filter_size
                    a_slice_prev = A_prev_pad[i, vert_start:vert_end, horiz_start:horiz_end, :]

                    # Step 3-2: Applying Filters
                    Z[i, h, w, c] = self.conv_single_step(a_slice_prev, self.parameters["W"][:,:,:,c], self.parameters["b"][:,:,:,c])

    ### END CODE HERE ###

    # Making sure your output shape is correct
    assert(Z.shape == (m, n_H, n_W, n_C))

    # Save information in "cache" for the backward pass
    self.cache = A_prev

    return Z

Conv.forward = forward

In [8]:
def backward(self, dZ):
    """
    Implement the backward propagation for a convolution layer

    Arguments:
    dZ -- gradient of the cost with respect to the output of the conv layer (Z), numpy array of shape (m, n_H, n_W, n_C)

    Returns:
    dA_prev -- gradient of the cost with respect to the input of the conv layer (A_prev),
                numpy array of shape (m, n_H_prev, n_W_prev, n_C_prev)
    """


    A_prev = self.cache

    ### START CODE HERE ###

    # Retrieve dimensions from A_prev's shape
    (m, n_H_prev, n_W_prev, n_C_prev) = A_prev.shape

    # Retrieve dimensions from W's shape
    (f, f, n_C_prev, n_C) = self.parameters["W"].shape

    # Retrieve dimensions from dZ's shape
    (m, n_H, n_W, n_C) = dZ.shape

    # Step 1: Initialize Gradients
    dA_prev = np.zeros((m, n_H_prev, n_W_prev, n_C_prev))
    dW = np.zeros((f, f, n_C_prev, n_C))
    db = np.zeros((1, 1, 1, n_C))

    # Step 2: Padding
    A_prev_pad = zero_pad(A_prev, self.pad)
    dA_prev_pad = zero_pad(dA_prev, self.pad)

    # Step 3: Loop Through Training Examples
    for i in range(m):                         # loop over the batch of training examples
        for h in range(n_H):                   # loop over vertical axis of the output volume
            for w in range(n_W):               # loop over horizontal axis of the output volume
                for c in range(n_C):           # loop over the channels of the output volume

                    # Step 3-1: Extracting slices
                    vert_start = h * self.stride
                    vert_end = vert_start + self.filter_size
                    horiz_start = w * self.stride
                    horiz_end = horiz_start + self.filter_size
                    a_slice = A_prev_pad[i, vert_start:vert_end, horiz_start:horiz_end, :]

                    # Step 3-2: Update the Gradients
                    dA_prev_pad[i, vert_start:vert_end, horiz_start:horiz_end, :] += self.parameters["W"][:,:,:,c] * dZ[i, h, w, c]
                    dW[:,:,:,c] = dW[:,:,:,c] + (1 / m)* a_slice * dZ[i, h, w, c]
                    db[:,:,:,c] = db[:,:,:,c] + (1/m) * dZ[i, h, w, c]

        # Step 4: Remove Padding
        dA_prev[i, :, :, :] = dA_prev_pad[i, self.pad:-self.pad, self.pad:-self.pad, :]

    ### END CODE HERE ###

    assert(dA_prev.shape == (m, n_H_prev, n_W_prev, n_C_prev))

    self.dW = dW
    self.db = db

    return dA_prev

Conv.backward = backward

In [9]:
def update(self, learning_rate):
    """
    Update parameters using gradient descent

    Arguments:
    learning rate -- step size
    """

    ### START CODE HERE ###
    self.parameters["W"] = self.parameters["W"] - learning_rate * self.dW
    self.parameters["b"] = self.parameters["b"] - learning_rate * self.db
    ### END CODE HERE ###

Conv.update = update

In [10]:
class MaxPool():
    def __init__(self, pool_size=2, stride=2):

        self.pool_size = pool_size
        self.stride = stride

    def create_mask_from_window(self, x):
        """
        Creates a mask from an input x to identify the max entry of x.

        Arguments:
        x -- Array of shape (filter_size, filter_size)

        Returns:
        mask -- Array of the same shape as filter, contains a True at the position corresponding to the max entry of x.
        """

        mask = x == np.max(x)

        return mask
    def forward(self, A_prev):
        """
        Implements the forward pass of the max pooling layer

        Arguments:
        A_prev -- Input data, numpy array of shape (m, n_H_prev, n_W_prev, n_C_prev)

        Returns:
        A -- output of the pool layer, a numpy array of shape (m, n_H, n_W, n_C)
        """

        ### START CODE HERE ###
        # retrieve dimensions from the input shape
        (m, n_H_prev, n_W_prev, n_C_prev) = A_prev.shape


        # Step 1: Output Dimension Calculation
        n_H = int((n_H_prev - self.pool_size)/self.stride) + 1
        n_W = int((n_W_prev - self.pool_size)/self.stride) + 1
        n_C = n_C_prev

        # initialize output matrix A with zeros
        A = np.zeros((m, n_H, n_W, n_C))

        # Step 2: Loop Through Training Examples
        for i in range(m):                           # loop over the batch of training examples
            for h in range(n_H):                     # loop on the vertical axis of the output volume
                for w in range(n_W):                 # loop on the horizontal axis of the output volume
                    for c in range (n_C):            # loop over the channels of the output volume

                        # Step 2-1: Extracting slices
                        vert_start = h * self.stride
                        vert_end = vert_start + self.pool_size
                        horiz_start = w * self.stride
                        horiz_end = horiz_start + self.pool_size
                        a_prev_slice = A_prev[i][vert_start:vert_end, horiz_start:horiz_end, c]

                        # Step 2-2: Applying Maxpooling
                        A[i, h, w, c] = np.max(a_prev_slice)

        ### END CODE HERE ###

        # Store the input in "cache" for backward pass
        self.cache = A_prev

        # Making sure your output shape is correct
        assert(A.shape == (m, n_H, n_W, n_C))

        return A

    def backward(self, dA):
        """
        Implements the backward pass of the max pooling layer

        Arguments:
        dA -- gradient of cost with respect to the output of the pooling layer, same shape as A

        Returns:
        dA_prev -- gradient of cost with respect to the input of the pooling layer, same shape as A_prev
        """

        # Retrieve information from cache
        A_prev = self.cache

        ### START CODE HERE ###

        # Retrieve dimensions from A_prev's shape and dA's shape
        m, n_H_prev, n_W_prev, n_C_prev = A_prev.shape
        m, n_H, n_W, n_C = dA.shape

        # Step 1: Initialize Gradients
        dA_prev = np.zeros((m, n_H_prev, n_W_prev, n_C_prev))

        # Step 2: Loop Through Training Examples
        for i in range(m):                           # loop over the batch of training examples
            for h in range(n_H):                     # loop on the vertical axis of the output volume
                for w in range(n_W):                 # loop on the horizontal axis of the output volume
                    for c in range (n_C):            # loop over the channels of the output volume

                        # Step 2-1: Extracting slices
                        vert_start = h * self.stride
                        vert_end = vert_start + self.pool_size
                        horiz_start = w * self.stride
                        horiz_end = horiz_start + self.pool_size
                        a_prev_slice = A_prev[i][vert_start:vert_end, horiz_start:horiz_end, c]

                        # Step 2-2: Pass through the Gradients
                        mask = self.create_mask_from_window(a_prev_slice)
                        dA_prev[i][vert_start:vert_end, horiz_start:horiz_end, c] = mask * dA[i, h, w, c]

        ### END CODE HERE ###

        # Make sure your output shape is correct

        assert(dA_prev.shape == A_prev.shape)

        return dA_prev



In [11]:
class Flatten():
    def __init__(self):
        pass

    def forward(self, A_prev):
        """
        Implements the forward pass of the flatten layer

        Arguments:
        A_prev -- Input data, numpy array of shape (m, n_H_prev, n_W_prev, n_C_prev)

        Returns:
        A -- output of the flatten layer, a 2-dimensional array of shape (m, (n_H_prev * n_W_prev * n_C_prev))
        """

        # Save information in "cache" for the backward pass
        self.cache = A_prev.shape

        ### START CODE HERE ###
        A = A_prev.reshape(A_prev.shape[0], -1)
        ### END CODE HERE ###
        return A

    def backward(self, dA):
        """
        Implements the backward pass of the flatten layer

        Arguments:
        dA -- Input data, a 2-dimensional array

        Returns:
        dA_prev -- An array with its original shape (the output shape of its' previous layer).
        """
        ### START CODE HERE ###
        dA_prev = dA.reshape(self.cache)
        ### END CODE HERE ###
        return dA_prev



In [12]:
class Model():
    def __init__(self):
        self.layers=[]

    def add(self, layer):
        self.layers.append(layer)

    def forward(self, X):
        A = X

        ### START CODE HERE ###
        for l in range(len(self.layers)):
            A = self.layers[l].forward(A)
        ### END CODE HERE ###
        return A

    def backward(self, AL=None, Y=None):
        L = len(self.layers)

        ### START CODE HERE ###
        e = 10**(-5)
        dAL = (-1)*(Y/(AL + e) - (1 - Y)/(1 - AL + e))
        # Lth layer (SIGMOID -> LINEAR) gradients. Inputs: "dAL". Outputs: "dA_prev"
        dZ = self.layers[L-1].backward(dA=dAL)
        dA_prev = self.layers[L-2].backward(dZ)
        # Loop from l=L-2 to l=0
        for l in reversed(range(L-2)):
            dA_prev = self.layers[l].backward(dA_prev)
        ### END CODE HERE ###

        return dA_prev

    def update(self, learning_rate):

        # Only convolution layer and dense layer have to update parameters
        ### START CODE HERE ###
        for l in range(len(self.layers)):
            if self.layers[l].__class__.__name__ == "Conv" or self.layers[l].__class__.__name__ == "Dense":
                self.layers[l].update(learning_rate)
        ### END CODE HERE ###


In [14]:
# Use np.load to load the data from npz file
### START CODE HERE ###
split_ratio = 0.1
split_index = int((1 - split_ratio) * len(data))
# Split the data into training and validation sets

permutation = list(np.random.permutation(data.shape[0]))
shuffled_X = data[permutation, : ]
shuffled_Y = labels[permutation, : ]

x1_train = shuffled_X[:split_index]
y1_train = shuffled_Y[:split_index]
x_val = shuffled_X[split_index:]
y_val = shuffled_Y[split_index:]
### END CODE HERE ###

# plot first few images
#for i in range(9):
    # define subplot
#    plt.subplot(330 + 1 + i)
    # plot raw pixel data
#    plt.imshow(x_train[i].squeeze(), cmap='gray', vmin=0, vmax=1)
#    plt.title(y_train[i])
# show the figure
#plt.show()

# check the shape of training data and testing data
print('Train: X=%s, y=%s' % (x1_train.shape, y1_train.shape))
print('Val: X=%s' % (x_val.shape, ))

#You can split training and validation set here using train_test_split (Optional)
### START CODE HERE ###
split_ratio = 0.8

# Split the data into training and validation sets

### END CODE HERE ###

Train: X=(6593, 180, 180, 1), y=(6593, 1)
Val: X=(733, 180, 180, 1)


In [15]:
def random_mini_batches(X, Y, mini_batch_size = 64):
    """
    Creates a list of random minibatches from (X, Y)

    Arguments:
    X -- input data, of shape !!!!!!!!!!!(number of examples ,input size)!!!!!!!!!!!
    Y -- true "label" vector, of shape (number of classes, number of examples)
    mini_batch_size -- size of the mini-batches, integer

    Returns:
    mini_batches -- list of synchronous (mini_batch_X, mini_batch_Y)
    """

    m = X.shape[0]  # number of training examples
    mini_batches = []

    # GRADED CODE: Binary classification
    ### START CODE HERE ###

    # Step 1: Shuffle (X, Y)
    permutation = list(np.random.permutation(m))
    shuffled_X = X[permutation, :]
    shuffled_Y = Y[permutation, :]

    inc = mini_batch_size

    # Step 2 - Partition (shuffled_X, shuffled_Y).
    # Cases with a complete mini batch size only i.e each of 64 examples.
    num_complete_minibatches = math.floor(m / mini_batch_size) # number of mini batches of size mini_batch_size in your partitionning
    for k in range(0, num_complete_minibatches):
        mini_batch_X = shuffled_X[k * mini_batch_size : (k+1) * mini_batch_size,:]
        mini_batch_Y = shuffled_Y[k * mini_batch_size : (k+1) * mini_batch_size,:]
        mini_batch = (mini_batch_X, mini_batch_Y)
        mini_batches.append(mini_batch)

    # For handling the end case (last mini-batch < mini_batch_size i.e less than 64)
    if m % mini_batch_size != 0:
        mini_batch_X = shuffled_X[num_complete_minibatches * mini_batch_size :,]
        mini_batch_Y = shuffled_Y[num_complete_minibatches * mini_batch_size :,]
        mini_batch = (mini_batch_X, mini_batch_Y)
        mini_batches.append(mini_batch)


    return mini_batches

    ### END CODE HERE ###

In [18]:
### START CODE HERE ###
learning_rate = 0.003
num_iterations = 8
batch_size = 64
costs = []   # keep track of cost


# Initialize the model
model = Model()

# Build the model by adding layers
model=Model()
model.add(Conv(filter_size=4, input_channel=3, output_channel=8, pad=2, stride=3))
model.add(MaxPool(pool_size=2, stride=2))
model.add(Flatten())
model.add(Dense(7200, 1024))
model.add(Activation("relu", None))
model.add(Dense(1024, 1))
model.add(Activation("sigmoid", None))

# Loop (gradient descent)
for i in range(0, num_iterations):
    print("epoch: ",i)
    mini_batches = random_mini_batches(x1_train, y1_train, batch_size)

    for batch in mini_batches:
        x_batch, y_batch = batch

        # forward
        AL = model.forward(x_batch)

        # compute cost
        cost = compute_BCE_loss(AL, y_batch)

        # backward
        dA_prev = model.backward(AL, y_batch)

        # update
        model.update(learning_rate)

    # AL = model.forward(A)
    # dA_prev = model.backward(AL=AL, Y=Y)
    print ("Cost after iteration %i: %f" %(i, cost))
    costs.append(cost)

### END CODE HERE ###

epoch:  0
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)
(64, 180, 180, 1)


In [23]:
weight = []

for i in range(len(model.layers)):
    if model.layers[i].__class__.__name__ == "Conv" or model.layers[i].__class__.__name__ == "Dense":
        weight.append(model.layers[i].parameters)
print(weight)

np.save('CNN_model.npy', weight)

[{'W': array([[[[-1.22679122e-01,  3.27077213e-01, -7.39078666e-01,
          -2.92005820e-01, -5.21650509e-01, -6.03953543e-01,
          -4.62009759e-01, -2.31798884e-01],
         [-1.52597046e-01,  5.89724840e-02, -1.20056275e-01,
           2.73555653e-01, -4.36427338e-01,  5.56718727e-01,
          -6.96680168e-01,  2.48120240e-01],
         [-1.22261402e-01,  8.83269899e-02, -5.31882357e-01,
          -4.45965334e-01,  4.44354789e-01,  6.89870445e-01,
          -2.74176132e-01,  2.80402371e-01]],

        [[ 5.55851123e-01,  5.84509039e-01, -6.13628983e-01,
          -6.80892888e-01, -4.87567171e-01,  5.56755753e-01,
          -5.91866424e-01, -1.20208720e-01],
         [ 6.76235160e-01,  5.06247406e-02,  2.82722618e-01,
          -2.72533153e-01,  2.75605747e-01,  4.92477133e-01,
          -7.10120749e-01,  3.65810681e-01],
         [ 7.21983184e-01,  3.68201333e-01, -3.25004379e-01,
           4.27262206e-01, -5.85948409e-01, -7.87641039e-02,
           6.04950178e-01, -3.0852

In [ ]:

pred_val = predict(model, x_val, y_val)

(733, 180, 180, 1)
Accuracy: 0.660300136425648


In [26]:
print(costs)

[-9.999950000398841e-06, -9.999950000398841e-06, -9.999950000398841e-06, -9.999950000398841e-06, -9.999950000398841e-06, -9.999950000398841e-06, 11.512925464970229, -9.999950000398841e-06]
